/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformPlatformRouteImport } from './routes/platform.$platform'
import { Route as PlayPlatformSlugRouteImport } from './routes/play.$platform.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformPlatformRoute = PlatformPlatformRouteImport.update({
  id: '/platform/$platform',
  path: '/platform/$platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayPlatformSlugRoute = PlayPlatformSlugRouteImport.update({
  id: '/play/$platform/$slug',
  path: '/play/$platform/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/platform/$platform': typeof PlatformPlatformRoute
  '/play/$platform/$slug': typeof PlayPlatformSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/platform/$platform': typeof PlatformPlatformRoute
  '/play/$platform/$slug': typeof PlayPlatformSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/platform/$platform': typeof PlatformPlatformRoute
  '/play/$platform/$slug': typeof PlayPlatformSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/platform/$platform' | '/play/$platform/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/platform/$platform' | '/play/$platform/$slug'
  id: '__root__' | '/' | '/platform/$platform' | '/play/$platform/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlatformPlatformRoute: typeof PlatformPlatformRoute
  PlayPlatformSlugRoute: typeof PlayPlatformSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/$platform': {
      id: '/platform/$platform'
      path: '/platform/$platform'
      fullPath: '/platform/$platform'
      preLoaderRoute: typeof PlatformPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$platform/$slug': {
      id: '/play/$platform/$slug'
      path: '/play/$platform/$slug'
      fullPath: '/play/$platform/$slug'
      preLoaderRoute: typeof PlayPlatformSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlatformPlatformRoute: PlatformPlatformRoute,
  PlayPlatformSlugRoute: PlayPlatformSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
